mautic_api.settings:
  type: config_object
  label: 'Mautic API settings'
  mapping:
    base_url:
      type: string
      label: 'Base url'
    basic_auth_username:
      type: string
      label: 'Username'
    basic_auth_password:
      type: string
      label: 'Password'
