mautic_api.settings:
  type: config_object
  label: 'Mautic API settings'
  mapping:
    base_url:
      type: string
      label: 'Base url'
    credential_provider:
      type: string
      label: 'Credential provider'
    credentials:
      type: sequence
      label: 'Credentials'
      sequence:
        type: mautic_api.settings.credentials.[%key]

mautic_api.settings.credentials.config:
  type: mapping
  label: 'Mautic API credentials'
  mapping:
    username:
      type: string
      label: 'Username key'
    password:
      type: string
      label: 'Password key'

mautic_api.settings.credentials.key:
  type: mapping
  label: 'Mautic API credentials with Key Module'
  mapping:
    username:
      type: string
      label: 'Username key'
    password:
      type: string
      label: 'Password key'

mautic_api.settings.credentials.multikey:
  type: mapping
  label: 'Mautic API credentials with Key Module (user/password keys)'
  mapping:
    user_password:
      type: string
      label: 'User/Password key'
